name: qdmr
#version: git
#grade: devel
version: 0.3.1
grade: stable
summary: Graphical codeplug programming tool DMR radios.
description: |
  qDMR is a simple to use and feature rich codeplug programming tool for cheap DMR radios.

confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  qdmr:
    command: qdmr
    desktop: usr/share/applications/qdmr.desktop
    plugs:
      - desktop
      - network
      - raw-usb
      - serial-port

parts:
  qdmr:
    plugin: cmake
    build-packages:
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtpositioning5-dev
      - libqt5serialport5-dev
      - libusb-1.0-0-dev
    stage-packages:
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5positioning5
      - libqt5serialport5
      - libqt5widgets5
      - libusb-1.0-0
    source: https://github.com/hmatuschek/qdmr.git
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
