name: qdmr
version: git
grade: devel
#version: 0.3.2
#grade: stable
summary: Graphical codeplug programming tool for DMR radios.
description: |
  qDMR is a simple to use and feature rich codeplug programming tool for cheap DMR radios.

confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  qdmr:
    command: qdmr
    desktop: usr/share/applications/qdmr.desktop
    extensions:
      - kde-neon
    plugs:
      - home
      - desktop
      - opengl
      - network
      - raw-usb
      - serial-port

parts:
  qdmr:
    plugin: cmake
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - libegl-dev
      - libusb-1.0-0-dev
    stage-packages:
      - libusb-1.0-0
    source: https://github.com/hmatuschek/qdmr.git
    source-type: git
#    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
